export const GET_CATEGORY = "GET_CATEGORY";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAILURE = "GET_CATEGORY_FAILURE";

export const GET_CURRENT_CATEGORY = "GET_CURRENT_CATEGORY";
export const GET_CURRENT_CATEGORY_SUCCESS = "GET_CURRENT_CATEGORY_SUCCESS";
export const GET_CURRENT_CATEGORY_FAILURE = "GET_CURRENT_CATEGORY_FAILURE";
export const CLEAR_CURRENT_CATEGORY = "CLEAR_CURRENT_CATEGORY";
