export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";

export const GET_TODOS = "GET_TODOS";
export const GET_TODOS_FAILED = "GET_TODOS_FAILED";
export const GET_TODOS_SUCCESS = "GET_TODOS_SUCCESS";

export const SET_TODOS = "SET_TODOS";

export const GET_CATEGORY = "GET_CATEGORY";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAILURE = "GET_CATEGORY_FAILURE";
