import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useDispatch, useSelector } from "react-redux";
import {
  decrementAction,
  incrementAction,
} from "../store/counter/Counter.action";
import { IRootState } from "../store/Root.reducer";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const router = useRouter();
  const dispatch = useDispatch();
  const { count } = useSelector((store: IRootState) => store.counter);

  const handleIncrement = () => dispatch(incrementAction());

  const handleDecrement = () => dispatch(decrementAction());

  const goToAbout = () => router.push("/unouthorized/about");

  const goToTodos = () => router.push("/unouthorized/todos");

  const goToCategory = () => router.push("/unouthorized/category");

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h3>{count}</h3>

        <div>
          <button onClick={handleIncrement}>+</button>

          <button onClick={handleDecrement}>-</button>
        </div>

        <button onClick={goToAbout}>To About Page</button>
        <button onClick={goToTodos}>To TODOS Page</button>
        <button onClick={goToCategory}>To CATEGORY Page</button>
        {/* <Link href={"/unouthorized/todos"}>GO to aaa</Link> */}
      </main>
    </div>
  );
};

export default Home;
